import sqlite3
conn = sqlite3.connect('app.db')
c = conn.cursor()
c.execute('SELECT COUNT(*) FROM users')
print(f'Users: {c.fetchone()[0]}')
c.execute("SELECT id, username, role FROM users WHERE role='admin' LIMIT 5")
print('Admins:', c.fetchall())
c.execute('SELECT COUNT(*) FROM ratings')
print(f'Ratings: {c.fetchone()[0]}')
c.execute('SELECT COUNT(*) FROM products')
print(f'Products: {c.fetchone()[0]}')
c.execute('SELECT COUNT(*) FROM favourites')
print(f'Favourites: {c.fetchone()[0]}')
conn.close()
